-- Localization.lua - Система локализации для TUMBA MEGA SYSTEM v5.0

return {
    -- Уведомления
    ["notify_enabled"] = { ru = "ВКЛЮЧЕНО", en = "ENABLED", es = "HABILITADO", pt = "ATIVADO", ko = "활성화됨", ja = "有効" },
    ["notify_disabled"] = { ru = "ВЫКЛЮЧЕН", en = "DISABLED", es = "DESHABILITADO", pt = "DESATIVADO", ko = "비활성화됨", ja = "無効" },
    ["notify_kit_esp_updated"] = { ru = "Kit ESP обновлен", en = "Kit ESP updated", es = "Kit ESP actualizado", pt = "Kit ESP atualizado", ko = "Kit ESP 업데이트됨", ja = "Kit ESP 更新されました" },
    ["notify_kit_esp_on"] = { ru = "Kit ESP включен", en = "Kit ESP enabled", es = "Kit ESP habilitado", pt = "Kit ESP ativado", ko = "Kit ESP 활성화됨", ja = "Kit ESP 有効" },
    ["notify_kit_esp_off"] = { ru = "Kit ESP выключен", en = "Kit ESP disabled", es = "Kit ESP deshabilitado", pt = "Kit ESP desativado", ko = "Kit ESP 비활성화됨", ja = "Kit ESP 無効" },
    ["notify_follow_start"] = { ru = "Слежение за %s включено", en = "Following %s enabled", es = "Seguimiento de %s habilitado", pt = "Seguindo %s ativado", ko = "%s 추적 활성화됨", ja = "%s 追跡有効" },
    ["notify_follow_stop"] = { ru = "Слежение отключено", en = "Following disabled", es = "Seguimiento deshabilitado", pt = "Seguindo desativado", ko = "추적 비활성화됨", ja = "追跡無効" },
    ["notify_config_saved"] = { ru = "Конфиг сохранен (#%d)", en = "Config saved (#%d)", es = "Configuración guardada (#%d)", pt = "Configuração salva (#%d)", ko = "설정 저장됨 (#%d)", ja = "設定保存 (#%d)" },
    ["notify_config_loaded"] = { ru = "Конфиг загружен", en = "Config loaded", es = "Configuración cargada", pt = "Configuração carregada", ko = "설정 로드됨", ja = "設定読み込み" },
    ["notify_config_not_found"] = { ru = "Конфиг не найден", en = "Config not found", es = "Configuración no encontrada", pt = "Configuração não encontrada", ko = "설정 없음", ja = "設定が見つかりません" },
    ["notify_settings_reset"] = { ru = "Настройки сброшены", en = "Settings reset", es = "Configuraciones restablecidas", pt = "Configurações redefinidas", ko = "설정 초기화됨", ja = "設定リセット" },
    ["notify_keybind_set"] = { ru = "%s привязана к %s", en = "%s bound to %s", es = "%s asignado a %s", pt = "%s vinculado a %s", ko = "%s가 %s에 바인딩됨", ja = "%s が %s にバインド" },
    ["notify_fov_color_changed"] = { ru = "🎨 Цвет FOV изменен", en = "🎨 FOV color changed", es = "🎨 Color de FOV cambiado", pt = "🎨 Cor do FOV alterada", ko = "🎨 FOV 색상 변경됨", ja = "🎨 FOV 色変更" },
    ["notify_team_color_changed"] = { ru = "🎨 Цвет команды изменен", en = "🎨 Team color changed", es = "🎨 Color del equipo cambiado", pt = "🎨 Cor do time alterada", ko = "🎨 팀 색상 변경됨", ja = "🎨 チーム色変更" },
    ["notify_enemy_color_changed"] = { ru = "🎨 Цвет врага изменен", en = "🎨 Enemy color changed", es = "🎨 Color del enemigo cambiado", pt = "🎨 Cor do inimigo alterada", ko = "🎨 적 색상 변경됨", ja = "🎨 敵色変更" },
    ["notify_theme_changed"] = { ru = "🎨 Цветовая тема изменена", en = "🎨 Theme color changed", es = "🎨 Tema de color cambiado", pt = "🎨 Tema de cor alterado", ko = "🎨 테마 색상 변경됨", ja = "🎨 テーマ色変更" },
    ["notify_chat_cleared"] = { ru = "🧹 Чат очищен", en = "🧹 Chat cleared", es = "🧹 Chat limpiado", pt = "🧹 Chat limpo", ko = "🧹 채팅 지워짐", ja = "🧹 チャットクリア" },
    ["notify_screenshot"] = { ru = "📸 Скриншот сохранен", en = "📸 Screenshot saved", es = "📸 Captura de pantalla guardada", pt = "📸 Screenshot salvo", ko = "📸 스크린샷 저장됨", ja = "📸 スクリーンショット保存" },
    ["notify_reload"] = { ru = "🔄 Скрипт перезагружается...", en = "🔄 Script reloading...", es = "🔄 Recargando script...", pt = "🔄 Recarregando script...", ko = "🔄 스크립트 재로드 중...", ja = "🔄 スクリプト再読み込み中..." },
    ["notify_cleanup"] = { ru = "🗑️ Скрипт выгружен", en = "🗑️ Script unloaded", es = "🗑️ Script descargado", pt = "🗑️ Script descarregado", ko = "🗑️ 스크립트 언로드됨", ja = "🗑️ スクリプトアンロード" },
           
    -- Ключи для вкладок
    ["tab_home"] = { ru = "🏠 ГЛАВНАЯ", en = "🏠 HOME", es = "🏠 INICIO", pt = "🏠 INÍCIO", ko = "🏠 홈", ja = "🏠 ホーム" },
    ["tab_esp"] = { ru = "👁️ ESP", en = "👁️ ESP", es = "👁️ ESP", pt = "👁️ ESP", ko = "👁️ ESP", ja = "👁️ ESP" },
    ["tab_aim"] = { ru = "🎯 AIM", en = "🎯 AIM", es = "🎯 PUNTERÍA", pt = "🎯 MIRA", ko = "🎯 조준", ja = "🎯 狙い" },
    ["tab_player"] = { ru = "⚡ ИГРОК", en = "⚡ PLAYER", es = "⚡ JUGADOR", pt = "⚡ JOGADOR", ko = "⚡ 플레이어", ja = "⚡ プレイヤー" },
    ["tab_combat"] = { ru = "🎮 БОЙ", en = "🎮 COMBAT", es = "🎮 COMBATE", pt = "🎮 COMBATE", ko = "🎮 전투", ja = "🎮 戦闘" },
    ["tab_visuals"] = { ru = "🌈 ВИЗУАЛЫ", en = "🌈 VISUALS", es = "🌈 VISUALES", pt = "🌈 VISUAIS", ko = "🌈 비주얼", ja = "🌈 ビジュアル" },
    ["tab_users"] = { ru = "👥 ИГРОКИ", en = "👥 PLAYERS", es = "👥 JUGADORES", pt = "👥 JOGADORES", ko = "👥 플레이어들", ja = "👥 プレイヤー" },
    ["tab_utils"] = { ru = "🔧 УТИЛИТЫ", en = "🔧 UTILITIES", es = "🔧 UTILIDADES", pt = "🔧 UTILITÁRIOS", ko = "🔧 유틸리티", ja = "🔧 ユーティリティ" },
    ["tab_settings"] = { ru = "⚙️ НАСТРОЙКИ", en = "⚙️ SETTINGS", es = "⚙️ AJUSTES", pt = "⚙️ CONFIGURAÇÕES", ko = "⚙️ 설정", ja = "⚙️ 設定" },

    -- GUI
    ["title_bar"] = { ru = "💎 TUMBA MEGA SYSTEM v%s 💎", en = "💎 TUMBA MEGA SYSTEM v%s 💎", es = "💎 SISTEMA MEGA TUMBA v%s 💎", pt = "💎 SISTEMA MEGA TUMBA v%s 💎", ko = "💎 TUMBA 메가 시스템 v%s 💎", ja = "💎 TUMBA メガシステム v%s 💎" },
    ["title_bar_with_tab"] = { ru = "💎 %s - TUMBA MEGA SYSTEM 💎", en = "💎 %s - TUMBA MEGA SYSTEM 💎", es = "💎 %s - SISTEMA MEGA TUMBA 💎", pt = "💎 %s - SISTEMA MEGA TUMBA 💎", ko = "💎 %s - TUMBA 메가 시스템 💎", ja = "💎 %s - TUMBA メガシステム 💎" },
    ["keybind_listening"] = { ru = "Нажмите клавишу...", en = "Press a key...", es = "Presiona una tecla...", pt = "Pressione uma tecla...", ko = "키를 누르세요...", ja = "キーを押してください..." },
    ["keybind_none"] = { ru = "Нет привязки", en = "None", es = "Ninguno", pt = "Nenhum", ko = "없음", ja = "なし" },
    ["keybind_current"] = { ru = "%s: %s", en = "%s: %s", es = "%s: %s", pt = "%s: %s", ko = "%s: %s", ja = "%s: %s" },
    ["slider_label"] = { ru = "%s: %s", en = "%s: %s", es = "%s: %s", pt = "%s: %s", ko = "%s: %s", ja = "%s: %s" },
    ["dropdown_label"] = { ru = " %s:", en = " %s:", es = " %s:", pt = " %s:", ko = " %s:", ja = " %s:" },

    -- Вкладка: Главная
    ["section_status"] = { ru = "💎 СИСТЕМНЫЙ СТАТУС", en = "💎 SYSTEM STATUS", es = "💎 ESTADO DEL SISTEMA", pt = "💎 STATUS DO SISTEMA", ko = "💎 시스템 상태", ja = "💎 システムステータス" },
    ["toggle_autosave"] = { ru = "🔄 Авто-сохранение конфигов", en = "🔄 Auto-save configs", es = "🔄 Guardado automático de configuraciones", pt = "🔄 Salvar configs automaticamente", ko = "🔄 자동 저장 설정", ja = "🔄 自動保存設定" },
    ["toggle_perf_mode"] = { ru = "⚡ Режим производительности", en = "⚡ Performance Mode", es = "⚡ Modo de rendimiento", pt = "⚡ Modo de desempenho", ko = "⚡ 성능 모드", ja = "⚡ パフォーマンスモード" },
    ["section_quick_access"] = { ru = "🚀 БЫСТРЫЙ ДОСТУП", en = "🚀 QUICK ACCESS", es = "🚀 ACCESO RÁPIDO", pt = "🚀 ACESSO RÁPIDO", ko = "🚀 빠른 액세스", ja = "🚀 クイックアクセス" },
    ["button_esp_toggle"] = { ru = "👁️ ВКЛ/ВЫКЛ ESP", en = "👁️ TOGGLE ESP", es = "👁️ ACTIVAR/DESACTIVAR ESP", pt = "👁️ LIGAR/DESLIGAR ESP", ko = "👁️ ESP 토글", ja = "👁️ ESP トグル" },
    ["button_aim_toggle"] = { ru = "🎯 ВКЛ/ВЫКЛ Aim Assist", en = "🎯 TOGGLE Aim Assist", es = "🎯 ACTIVAR/DESACTIVAR Ayuda de puntería", pt = "🎯 LIGAR/DESLIGAR Assistência de Mira", ko = "🎯 조준 보조 토글", ja = "🎯 エイムアシスト トグル" },
    ["button_speed_toggle"] = { ru = "⚡ ВКЛ/ВЫКЛ Speed Hack", en = "⚡ TOGGLE Speed Hack", es = "⚡ ACTIVAR/DESACTIVAR Hack de velocidad", pt = "⚡ LIGAR/DESLIGAR Hack de Velocidade", ko = "⚡ 속도 해킹 토글", ja = "⚡ スピードハック トグル" },
    ["section_stats"] = { ru = "📊 СТАТИСТИКА СИСТЕМЫ", en = "📊 SYSTEM STATISTICS", es = "📊 ESTADÍSTICAS DEL SISTEMA", pt = "📊 ESTATÍSTICAS DO SISTEMA", ko = "📊 시스템 통계", ja = "📊 システム統計" },
    ["stats_label"] = { ru = "📈 СТАТИСТИКА:\n🎯 Убийств: %d\n💀 Смертей: %d\n🎮 Время игры: %dм\n💾 Конфигов сохранено: %d", en = "📈 STATISTICS:\n🎯 Kills: %d\n💀 Deaths: %d\n🎮 Play Time: %dm\n💾 Config Saves: %d", es = "📈 ESTADÍSTICAS:\n🎯 Asesinatos: %d\n💀 Muertes: %d\n🎮 Tiempo de juego: %dm\n💾 Guardados de config: %d", pt = "📈 ESTATÍSTICAS:\n🎯 Mortes: %d\n💀 Mortes: %d\n🎮 Tempo de jogo: %dm\n💾 Salvar configs: %d", ko = "📈 통계:\n🎯 킬: %d\n💀 데스: %d\n🎮 플레이 시간: %dm\n💾 설정 저장: %d", ja = "📈 統計:\n🎯 キル: %d\n💀 デス: %d\n🎮 プレイ時間: %dm\n💾 設定保存: %d" },

    -- Вкладка: ESP
    ["section_esp_main"] = { ru = "👁️ ОСНОВНЫЕ НАСТРОЙКИ ESP (Игроки)", en = "👁️ MAIN ESP SETTINGS (Players)", es = "👁️ CONFIGURACIONES PRINCIPALES DE ESP (Jugadores)", pt = "👁️ CONFIGURAÇÕES PRINCIPAIS DE ESP (Jogadores)", ko = "👁️ 주요 ESP 설정 (플레이어)", ja = "👁️ メインESP設定 (プレイヤー)" },
    ["toggle_esp"] = { ru = "Включить ESP", en = "Enable ESP", es = "Habilitar ESP", pt = "Ativar ESP", ko = "ESP 활성화", ja = "ESP 有効" },
    ["section_esp_visuals"] = { ru = "⚙️ НАСТРОЙКИ ВИЗУАЛОВ", en = "⚙️ VISUALS SETTINGS", es = "⚙️ CONFIGURACIONES VISUALES", pt = "⚙️ CONFIGURAÇÕES VISUAIS", ko = "⚙️ 비주얼 설정", ja = "⚙️ ビジュアル設定" },
    ["toggle_esp_boxes"] = { ru = "Показывать боксы", en = "Show Boxes", es = "Mostrar Cajas", pt = "Mostrar Caixas", ko = "박스 표시", ja = "ボックス表示" },
    ["toggle_esp_names"] = { ru = "Показывать имена", en = "Show Names", es = "Mostrar Nombres", pt = "Mostrar Nomes", ko = "이름 표시", ja = "名前表示" },
    ["toggle_esp_health"] = { ru = "Показывать здоровье", en = "Show Health", es = "Mostrar Salud", pt = "Mostrar Saúde", ko = "체력 표시", ja = "ヘルス表示" },
    ["toggle_esp_distance"] = { ru = "Показывать дистанцию", en = "Show Distance", es = "Mostrar Distancia", pt = "Mostrar Distância", ko = "거리 표시", ja = "距離表示" },
    ["toggle_esp_tracers"] = { ru = "Показывать трейсеры", en = "Show Tracers", es = "Mostrar Rastreadores", pt = "Mostrar Traçadores", ko = "추적자 표시", ja = "トレーサー表示" },
    ["toggle_esp_team"] = { ru = "Показывать команду", en = "Show Team", es = "Mostrar Equipo", pt = "Mostrar Time", ko = "팀 표시", ja = "チーム表示" },
    ["slider_esp_max_dist"] = { ru = "Макс. дистанция ESP", en = "Max ESP Distance", es = "Distancia máxima de ESP", pt = "Distância máxima do ESP", ko = "최대 ESP 거리", ja = "最大ESP距離" },
    ["section_esp_colors"] = { ru = "🎨 ЦВЕТА ESP", en = "🎨 ESP COLORS", es = "🎨 COLORES DE ESP", pt = "🎨 CORES DO ESP", ko = "🎨 ESP 색상", ja = "🎨 ESP 色" },
    ["button_team_color"] = { ru = "🎨 Изменить цвет команды", en = "🎨 Change Team Color", es = "🎨 Cambiar Color del Equipo", pt = "🎨 Alterar Cor do Time", ko = "🎨 팀 색상 변경", ja = "🎨 チーム色変更" },
    ["button_enemy_color"] = { ru = "🎨 Изменить цвет врага", en = "🎨 Change Enemy Color", es = "🎨 Cambiar Color del Enemigo", pt = "🎨 Alterar Cor do Inimigo", ko = "🎨 적 색상 변경", ja = "🎨 敵色変更" },
    ["section_kit_esp"] = { ru = "🛠️ KIT ESP (Ресурсы и Киты)", en = "🛠️ KIT ESP (Resources & Kits)", es = "🛠️ KIT ESP (Recursos y Kits)", pt = "🛠️ KIT ESP (Recursos e Kits)", ko = "🛠️ KIT ESP (자원 및 키트)", ja = "🛠️ KIT ESP (리ソースとキット)" },
    ["toggle_kit_esp"] = { ru = "Включить Kit ESP", en = "Enable Kit ESP", es = "Habilitar Kit ESP", pt = "Ativar Kit ESP", ko = "Kit ESP 활성화", ja = "Kit ESP 有効" },
    ["section_kit_filters"] = { ru = "⚙️ ФИЛЬТРЫ", en = "⚙️ FILTERS", es = "⚙️ FILTROS", pt = "⚙️ FILTROS", ko = "⚙️ 필터", ja = "⚙️ フィルター" },
    ["toggle_kit_iron"] = { ru = "Показывать: Руда (Iron)", en = "Show: Ore (Iron)", es = "Mostrar: Mineral (Hierro)", pt = "Mostrar: Minério (Ferro)", ko = "표시: 광석 (철)", ja = "表示: 鉱石 (鉄)" },
    ["toggle_kit_bee"] = { ru = "Показывать: Пчелиные соты (Bee)", en = "Show: Honeycomb (Bee)", es = "Mostrar: Panal (Abeja)", pt = "Mostrar: Favo (Abelha)", ko = "표시: 벌집 (벌)", ja = "表示: 蜂の巣 (蜂)" },
    ["toggle_kit_essence"] = { ru = "Показывать: Эссенция (Nature Essence)", en = "Show: Essence (Nature Essence)", es = "Mostrar: Esencia (Esencia de Naturaleza)", pt = "Mostrar: Essência (Essência Natural)", ko = "표시: 에센스 (자연 에센스)", ja = "表示: 本質 (自然の本質)" },
    ["toggle_kit_thorns"] = { ru = "Показывать: Шипы (Thorns)", en = "Show: Thorns", es = "Mostrar: Espinas", pt = "Mostrar: Espinhos", ko = "표시: 가시", ja = "表示: 棘" },
    ["toggle_kit_mushrooms"] = { ru = "Показывать: Грибы (Mushrooms)", en = "Show: Mushrooms", es = "Mostrar: Hongos", pt = "Mostrar: Cogumelos", ko = "표시: 버섯", ja = "表示: きのこ" },
    ["toggle_kit_critstar"] = { ru = "Показывать: Звезда Крита (Crit Star)", en = "Show: Crit Star", es = "Mostrar: Estrella Crítica", pt = "Mostrar: Estrela Crítica", ko = "표시: 크리티컬 스타", ja = "表示: クリットスター" },
    ["toggle_kit_vitstar"] = { ru = "Показывать: Звезда Жизни (Vitality Star)", en = "Show: Vitality Star", es = "Mostrar: Estrella de Vitalidad", pt = "Mostrar: Estrela de Vitalidade", ko = "표시: 바이탈리티 스타", ja = "表示: バイタリティスター" },
    ["button_kit_esp_apply"] = { ru = "🔄 Применить и Обновить Kit ESP", en = "🔄 Apply and Refresh Kit ESP", es = "🔄 Aplicar y Actualizar Kit ESP", pt = "🔄 Aplicar e Atualizar Kit ESP", ko = "🔄 Kit ESP 적용 및 새로고침", ja = "🔄 Kit ESP 適用と更新" },

    -- Вкладка: Aim
    ["section_aim_main"] = { ru = "🎯 ОСНОВНЫЕ НАСТРОЙКИ AIM", en = "🎯 MAIN AIM SETTINGS", es = "🎯 CONFIGURACIONES PRINCIPALES DE PUNTERÍA", pt = "🎯 CONFIGURAÇÕES PRINCIPAIS DE MIRA", ko = "🎯 주요 조준 설정", ja = "🎯 メインエイム設定" },
    ["toggle_aim"] = { ru = "Включить Aim Assist", en = "Enable Aim Assist", es = "Habilitar Ayuda de Puntería", pt = "Ativar Assistência de Mira", ko = "조준 보조 활성화", ja = "エイムアシスト有効" },
    ["section_aim_settings"] = { ru = "⚙️ НАСТРОЙКИ ПАРАМЕТРОВ", en = "⚙️ PARAMETER SETTINGS", es = "⚙️ CONFIGURACIONES DE PARÁMETROS", pt = "⚙️ CONFIGURAÇÕES DE PARÂMETROS", ko = "⚙️ 매개변수 설정", ja = "⚙️ パラメータ設定" },
    ["toggle_aim_show_fov"] = { ru = "Показывать FOV", en = "Show FOV", es = "Mostrar FOV", pt = "Mostrar FOV", ko = "FOV 표시", ja = "FOV 表示" },
    ["button_aim_fov_color"] = { ru = "🎨 Изменить цвет FOV", en = "🎨 Change FOV Color", es = "🎨 Cambiar Color de FOV", pt = "🎨 Alterar Cor do FOV", ko = "🎨 FOV 색상 변경", ja = "🎨 FOV 色変更" },
    ["dropdown_aim_target"] = { ru = "Цель прицела", en = "Aim Target", es = "Objetivo de Puntería", pt = "Alvo da Mira", ko = "조준 목표", ja = "エイムターゲット" },
    ["dropdown_aim_target_head"] = { ru = "Head (Голова)", en = "Head", es = "Cabeza", pt = "Cabeça", ko = "머리", ja = "頭" },
    ["dropdown_aim_target_upper"] = { ru = "UpperTorso (Верхняя часть тела)", en = "UpperTorso", es = "Torso Superior", pt = "Torso Superior", ko = "상체", ja = "上半身" },
    ["dropdown_aim_target_lower"] = { ru = "LowerTorso (Нижняя часть тела)", en = "LowerTorso", es = "Torso Inferior", pt = "Torso Inferior", ko = "하체", ja = "下半身" },
    ["dropdown_aim_target_root"] = { ru = "HumanoidRootPart (Центр)", en = "HumanoidRootPart (Center)", es = "ParteRaízHumanoide (Centro)", pt = "ParteRaizHumanoide (Centro)", ko = "휴머노이드 루트 파트 (중심)", ja = "ヒューマノイドルートパート (中心)" },
    ["slider_aim_fov"] = { ru = "FOV прицела", en = "Aim FOV", es = "FOV de Puntería", pt = "FOV da Mira", ko = "조준 FOV", ja = "エイムFOV" },
    ["slider_aim_smooth"] = { ru = "Плавность", en = "Smoothness", es = "Suavidad", pt = "Suavidade", ko = "부드러움", ja = "滑らかさ" },
    ["slider_aim_range"] = { ru = "Дальность", en = "Range", es = "Rango", pt = "Alcance", ko = "범위", ja = "範囲" },
    ["section_aim_key"] = { ru = "🎯 КЛАВИША AIM", en = "🎯 AIM KEY", es = "🎯 TECLA DE PUNTERÍA", pt = "🎯 TECLA DE MIRA", ko = "🎯 조준 키", ja = "🎯 エイムキー" },
    ["keybind_aim"] = { ru = "🔑 Изменить клавишу Aim", en = "🔑 Change Aim Key", es = "🔑 Cambiar Tecla de Puntería", pt = "🔑 Alterar Tecla de Mira", ko = "🔑 조준 키 변경", ja = "🔑 エイムキー変更" },
    ["toggle_aim_silent"] = { ru = "Тихий прицел", en = "Silent Aim", es = "Puntería Silenciosa", pt = "Mira Silenciosa", ko = "무음 조준", ja = "サイレントエイム" },
    ["toggle_aim_prediction"] = { ru = "Предсказание движения", en = "Movement Prediction", es = "Predicción de Movimiento", pt = "Previsão de Movimento", ko = "움직임 예측", ja = "移動予測" },

    -- Вкладка: Игрок
    ["section_player_movement"] = { ru = "⚡ ДВИЖЕНИЕ", en = "⚡ MOVEMENT", es = "⚡ MOVIMIENTO", pt = "⚡ MOVIMENTO", ko = "⚡ 이동", ja = "⚡ 移動" },
    ["toggle_speed"] = { ru = "Спидхак", en = "Speedhack", es = "Hack de Velocidad", pt = "Hack de Velocidade", ko = "속도 해킹", ja = "スピードハック" },
    ["slider_speed"] = { ru = "Скорость", en = "Speed", es = "Velocidad", pt = "Velocidade", ko = "속도", ja = "速度" },
    ["toggle_fly"] = { ru = "Режим полета", en = "Fly Mode", es = "Modo Vuelo", pt = "Modo Voo", ko = "비행 모드", ja = "フライモード" },
    ["toggle_inf_jump"] = { ru = "Бесконечный прыжок", en = "Infinite Jump", es = "Salto Infinito", pt = "Pulo Infinito", ko = "무한 점프", ja = "無限ジャンプ" },
    ["section_player_defense"] = { ru = "🛡️ ЗАЩИТА", en = "🛡️ DEFENSE", es = "🛡️ DEFENSA", pt = "🛡️ DEFESA", ko = "🛡️ 방어", ja = "🛡️ 防御" },
    ["toggle_godmode"] = { ru = "Режим бога", en = "God Mode", es = "Modo Dios", pt = "Modo Deus", ko = "갓 모드", ja = "ゴッドモード" },
    ["toggle_noclip"] = { ru = "Ноклип", en = "Noclip", es = "Noclip", pt = "Noclip", ko = "노클립", ja = "ノークリップ" },

    -- Вкладка: Бой
    ["section_combat_auto"] = { ru = "🎯 АВТОМАТИЗАЦИЯ", en = "🎯 AUTOMATION", es = "🎯 AUTOMATIZACIÓN", pt = "🎯 AUTOMAÇÃO", ko = "🎯 자동화", ja = "🎯 自動化" },
    ["toggle_triggerbot"] = { ru = "Триггер-бот", en = "Trigger Bot", es = "Bot de Disparador", pt = "Bot de Gatilho", ko = "트리거 봇", ja = "トリガーボット" },
    ["toggle_autoshoot"] = { ru = "Авто-стрельба", en = "Auto Shoot", es = "Disparo Automático", pt = "Tiro Automático", ko = "자동 사격", ja = "オートシュート" },
    ["toggle_rapidfire"] = { ru = "Быстрая стрельба", en = "Rapid Fire", es = "Fuego Rápido", pt = "Fogo Rápido", ko = "급속 사격", ja = "ラピッドファイア" },
    ["section_combat_accuracy"] = { ru = "🎯 ТОЧНОСТЬ", en = "🎯 ACCURACY", es = "🎯 PRECISIÓN", pt = "🎯 PRECISÃO", ko = "🎯 정확도", ja = "🎯 精度" },
    ["toggle_norecoil"] = { ru = "Нет отдачи", en = "No Recoil", es = "Sin Retroceso", pt = "Sem Recuo", ko = "반동 없음", ja = "反動なし" },
    ["toggle_nospread"] = { ru = "Нет разброса", en = "No Spread", es = "Sin Dispersión", pt = "Sem Espalhamento", ko = "흩어짐 없음", ja = "拡散なし" },

    -- Вкладка: Визуалы
    ["section_visuals_env"] = { ru = "🌍 ОКРУЖЕНИЕ", en = "🌍 ENVIRONMENT", es = "🌍 ENTORNO", pt = "🌍 AMBIENTE", ko = "🌍 환경", ja = "🌍 環境" },
    ["button_visuals_settings"] = { ru = "⚙️ Настроить Визуалы Среды (NoFog, Brightness, Shadows)", en = "⚙️ Adjust Environment Visuals (NoFog, Brightness, Shadows)", es = "⚙️ Ajustar Visuales del Entorno (SinNiebla, Brillo, Sombras)", pt = "⚙️ Ajustar Visuais do Ambiente (Sem Névoa, Brilho, Sombras)", ko = "⚙️ 환경 비주얼 조정 (안개 없음, 밝기, 그림자)", ja = "⚙️ 環境ビジュアル調整 (霧なし、明るさ、影)" },
    ["toggle_nofog"] = { ru = "Убрать туман", en = "Remove Fog", es = "Eliminar Niebla", pt = "Remover Névoa", ko = "안개 제거", ja = "霧除去" },
    ["toggle_fullbright"] = { ru = "Яркое освещение", en = "Full Bright", es = "Brillo Completo", pt = "Brilho Total", ko = "전체 밝기", ja = "フルブライト" },
    ["toggle_nightmode"] = { ru = "Ночной режим", en = "Night Mode", es = "Modo Noche", pt = "Modo Noite", ko = "야간 모드", ja = "ナイトモード" },
    ["toggle_removeshadows"] = { ru = "Убрать тени", en = "Remove Shadows", es = "Eliminar Sombras", pt = "Remover Sombras", ko = "그림자 제거", ja = "影除去" },

    -- Вкладка: Утилиты
    ["section_utils_tools"] = { ru = "🔧 ИНСТРУМЕНТЫ", en = "🔧 TOOLS", es = "🔧 HERRAMIENTAS", pt = "🔧 FERRAMENTAS", ko = "🔧 도구", ja = "🔧 ツール" },
    ["button_clear_chat"] = { ru = "🧹 Очистить игровой чат", en = "🧹 Clear Game Chat", es = "🧹 Limpiar Chat del Juego", pt = "🧹 Limpar Chat do Jogo", ko = "🧹 게임 채팅 지우기", ja = "🧹 ゲームチャットクリア" },
    ["button_screenshot"] = { ru = "📸 Сделать скриншот", en = "📸 Take Screenshot", es = "📸 Tomar Captura de Pantalla", pt = "📸 Tirar Screenshot", ko = "📸 스크린샷 찍기", ja = "📸 スクリーンショット" },
    ["button_server_info"] = { ru = "🔍 Информация об сервере", en = "🔍 Server Info", es = "🔍 Información del Servidor", pt = "🔍 Info do Servidor", ko = "🔍 서버 정보", ja = "🔍 サーバー情報" },
    ["section_utils_fun"] = { ru = "🎪 РАЗВЛЕЧЕНИЯ", en = "🎪 MISC", es = "🎪 VARIOS", pt = "🎪 DIVERSOS", ko = "🎪 기타", ja = "🎪 雑多" },
    ["toggle_fame_spam"] = { ru = "Спам в чат", en = "Chat Spam", es = "Spam de Chat", pt = "Spam no Chat", ko = "채팅 스팸", ja = "チャットスパム" },
    ["button_reload_script"] = { ru = "🔄 Релоад скрипта", en = "🔄 Reload Script", es = "🔄 Recargar Script", pt = "🔄 Recarregar Script", ko = "🔄 스크립트 재로드", ja = "🔄 スクリプト再読み込み" },

    -- Вкладка: Настройки
    ["section_settings_appearance"] = { ru = "🎨 ВНЕШНИЙ ВИД", en = "🎨 APPEARANCE", es = "🎨 APARIENCIA", pt = "🎨 APARECÊNCIA", ko = "🎨 외관", ja = "🎨 外観" },
    ["button_change_theme"] = { ru = "🌈 Сменить цветовую тему", en = "🌈 Change Color Theme", es = "🌈 Cambiar Tema de Color", pt = "🌈 Alterar Tema de Cor", ko = "🌈 색상 테마 변경", ja = "🌈 カラーテーマ変更" },
    ["keybind_menu"] = { ru = "🔑 Изменить клавишу меню", en = "🔑 Change Menu Key", es = "🔑 Cambiar Tecla del Menú", pt = "🔑 Alterar Tecla do Menu", ko = "🔑 메뉴 키 변경", ja = "🔑 メニューキー変更" },
    ["section_settings_config"] = { ru = "💾 УПРАВЛЕНИЕ КОНФИГАМИ", en = "💾 CONFIG MANAGEMENT", es = "💾 GESTIÓN DE CONFIGURACIONES", pt = "💾 GERENCIAMENTO DE CONFIG", ko = "💾 설정 관리", ja = "💾 設定管理" },
    ["button_config_save"] = { ru = "💾 Сохранить конфиг", en = "💾 Save Config", es = "💾 Guardar Configuración", pt = "💾 Salvar Configuração", ko = "💾 설정 저장", ja = "💾 設定保存" },
    ["button_config_load"] = { ru = "📂 Загрузить конфиг", en = "📂 Load Config", es = "📂 Cargar Configuración", pt = "📂 Carregar Configuração", ko = "📂 설정 로드", ja = "📂 設定読み込み" },
    ["button_config_reset"] = { ru = "🔄 Сбросить настройки", en = "🔄 Reset Settings", es = "🔄 Restablecer Configuraciones", pt = "🔄 Redefinir Configurações", ko = "🔄 설정 초기화", ja = "🔄 設定リセット" },
    ["button_cleanup"] = { ru = "🗑️ Очистить и выгрузить скрипт", en = "🗑️ Cleanup and Unload Script", es = "🗑️ Limpiar y Descargar Script", pt = "🗑️ Limpar e Descarregar Script", ko = "🗑️ 정리 및 스크립트 언로드", ja = "🗑️ クリーンアップとスクリプトアンロード" },

    -- Вкладка: Игроки
    ["section_player_list"] = { ru = "👥 СПИСОК ИГРОКОВ НА СЕРВЕРЕ", en = "👥 SERVER PLAYER LIST", es = "👥 LISTA DE JUGADORES DEL SERVIDOR", pt = "👥 LISTA DE JOGADORES DO SERVIDOR", ko = "👥 서버 플레이어 목록", ja = "👥 サーバープレイヤーリスト" },
    ["button_stop_follow"] = { ru = "❌ Отключить слежение", en = "❌ Stop Following", es = "❌ Detener Seguimiento", pt = "❌ Parar Seguindo", ko = "❌ 추적 중지", ja = "❌ 追跡停止" },
    ["playerlist_name"] = { ru = "ИМЯ", en = "NAME", es = "NOMBRE", pt = "NOME", ko = "이름", ja = "名前" },
    ["playerlist_team"] = { ru = "КОМАНДА", en = "TEAM", es = "EQUIPO", pt = "TIME", ko = "팀", ja = "チーム" },
    ["playerlist_hp"] = { ru = "HP", en = "HP", es = "HP", pt = "HP", ko = "HP", ja = "HP" },
    ["playerlist_dist"] = { ru = "ДИСТ.", en = "DIST.", es = "DIST.", pt = "DIST.", ko = "거리.", ja = "DIST." },
    ["playerlist_team_none"] = { ru = "НЕТ", en = "NONE", es = "NINGUNO", pt = "NENHUM", ko = "없음", ja = "なし" },
    ["playerlist_hp_dead"] = { ru = "HP: DEAD", en = "HP: DEAD", es = "HP: MUERTO", pt = "HP: MORTO", ko = "HP: 죽음", ja = "HP: デッド" },
    ["playerlist_hp_format"] = { ru = "HP: %d", en = "HP: %d", es = "HP: %d", pt = "HP: %d", ko = "HP: %d", ja = "HP: %d" },
    ["playerlist_dist_none"] = { ru = "ДИСТ: ---", en = "DIST: ---", es = "DIST: ---", pt = "DIST: ---", ko = "거리: ---", ja = "DIST: ---" },
    ["playerlist_dist_format"] = { ru = "ДИСТ: %dм", en = "DIST: %dm", es = "DIST: %dm", pt = "DIST: %dm", ko = "거리: %dm", ja = "DIST: %dm" },

    -- Сообщения в консоль (print)
    ["print_esp_on"] = { ru = "👁️ ESP: ВКЛЮЧЕН", en = "👁️ ESP: ENABLED", es = "👁️ ESP: HABILITADO", pt = "👁️ ESP: ATIVADO", ko = "👁️ ESP: 활성화됨", ja = "👁️ ESP: 有効" },
    ["print_esp_off"] = { ru = "👁️ ESP: ВЫКЛЮЧЕН", en = "👁️ ESP: DISABLED", es = "👁️ ESP: DESHABILITADO", pt = "👁️ ESP: DESATIVADO", ko = "👁️ ESP: 비활성화됨", ja = "👁️ ESP: 無効" },
    ["print_aim_on"] = { ru = "🎯 Aim Assist: ВКЛЮЧЕН", en = "🎯 Aim Assist: ENABLED", es = "🎯 Ayuda de Puntería: HABILITADA", pt = "🎯 Assistência de Mira: ATIVADA", ko = "🎯 조준 보조: 활성화됨", ja = "🎯 エイムアシスト: 有効" },
    ["print_aim_off"] = { ru = "🎯 Aim Assist: ВЫКЛЮЧЕН", en = "🎯 Aim Assist: DISABLED", es = "🎯 Ayuda de Puntería: DESHABILITADA", pt = "🎯 Assistência de Mira: DESATIVADA", ko = "🎯 조준 보조: 비활성화됨", ja = "🎯 エイムアシスト: 無効" },
    ["print_aim_active"] = { ru = "🎯 Aim Assist АКТИВИРОВАН", en = "🎯 Aim Assist ACTIVATED", es = "🎯 Ayuda de Puntería ACTIVADA", pt = "🎯 Assistência de Mira ATIVADA", ko = "🎯 조준 보조 활성화됨", ja = "🎯 エイムアシスト アクティブ" },
    ["print_aim_inactive"] = { ru = "🎯 Aim Assist ДЕАКТИВИРОВАН", en = "🎯 Aim Assist DEACTIVATED", es = "🎯 Ayuda de Puntería DESACTIVADA", pt = "🎯 Assistência de Mira DESATIVADA", ko = "🎯 조준 보조 비활성화됨", ja = "🎯 エイムアシスト 非アクティブ" },
    ["print_speed_on"] = { ru = "⚡ Speed Hack: %s единиц", en = "⚡ Speed Hack: %s units", es = "⚡ Hack de Velocidad: %s unidades", pt = "⚡ Hack de Velocidade: %s unidades", ko = "⚡ 속도 해킹: %s 유닛", ja = "⚡ スピードハック: %s ユニット" },
    ["print_speed_off"] = { ru = "⚡ Speed Hack: 16 единиц", en = "⚡ Speed Hack: 16 units", es = "⚡ Hack de Velocidad: 16 unidades", pt = "⚡ Hack de Velocidade: 16 unidades", ko = "⚡ 속도 해킹: 16 유닛", ja = "⚡ スピードハック: 16 ユニット" },
    ["print_load_success"] = { ru = "🔥 TUMBA MEGA SYSTEM v%s УСПЕШНО ЗАГРУЖЕН!", en = "🔥 TUMBA MEGA SYSTEM v%s LOADED SUCCESSFULLY!", es = "🔥 SISTEMA MEGA TUMBA v%s CARGADO EXITOSAMENTE!", pt = "🔥 SISTEMA MEGA TUMBA v%s CARREGADO COM SUCESSO!", ko = "🔥 TUMBA 메가 시스템 v%s 성공적으로 로드됨!", ja = "🔥 TUMBA メガシステム v%s 正常に読み込まれました!" },
    ["print_created_by"] = { ru = "💎 Создано: %s", en = "💎 Created by: %s", es = "💎 Creado por: %s", pt = "💎 Criado por: %s", ko = "💎 제작: %s", ja = "💎 作成: %s" },
    ["print_for"] = { ru = "🎯 Специально для: %s", en = "🎯 Especially for: %s", es = "🎯 Especialmente para: %s", pt = "🎯 Especialmente para: %s", ko = "🎯 특별히 위해: %s", ja = "🎯 特にために: %s" },
    ["print_build_date"] = { ru = "📅 Сборка: %s", en = "📅 Build: %s", es = "📅 Compilación: %s", pt = "📅 Compilação: %s", ko = "📅 빌드: %s", ja = "📅 ビルド: %s" },
    ["print_menu_key"] = { ru = "🎮 Используйте %s для открытия меню", en = "🎮 Use %s to open the menu", es = "🎮 Usa %s para abrir el menú", pt = "🎮 Use %s para abrir o menu", ko = "🎮 메뉴 열기에 %s 사용", ja = "🎮 メニューを開くために %s を使用" },
    ["print_esp_ready"] = { ru = "👁️ ESP готов к использованию", en = "👁️ ESP is ready to use", es = "👁️ ESP listo para usar", pt = "👁️ ESP pronto para usar", ko = "👁️ ESP 사용 준비됨", ja = "👁️ ESP 使用準備完了" },
    ["print_kit_esp_ready"] = { ru = "🛠️ Kit ESP добавлен и готов к использованию", en = "🛠️ Kit ESP added and ready to use", es = "🛠️ Kit ESP agregado y listo para usar", pt = "🛠️ Kit ESP adicionado e pronto para usar", ko = "🛠️ Kit ESP 추가 및 사용 준비됨", ja = "🛠️ Kit ESP 追加され使用準備完了" },
    ["print_aim_ready"] = { ru = "🎯 Aim Assist готов (Нажми %s для активации)", en = "🎯 Aim Assist ready (Press %s to activate)", es = "🎯 Ayuda de Puntería lista (Presiona %s para activar)", pt = "🎯 Assistência de Mira pronta (Pressione %s para ativar)", ko = "🎯 조준 보조 준비됨 (%s 누르기 활성화)", ja = "🎯 エイムアシスト 準備完了 (%s を押してアクティブ)" },
    ["print_all_ready"] = { ru = "⚡ Все функции активированы!", en = "⚡ All functions activated!", es = "⚡ ¡Todas las funciones activadas!", pt = "⚡ Todas as funções ativadas!", ko = "⚡ 모든 기능 활성화됨!", ja = "⚡ すべての機能がアクティブ!" },
    ["print_menu_open"] = { ru = "🚀 TUMBA MEGA SYSTEM v%s АКТИВИРОВАН", en = "🚀 TUMBA MEGA SYSTEM v%s ACTIVATED", es = "🚀 SISTEMA MEGA TUMBA v%s ACTIVADO", pt = "🚀 SISTEMA MEGA TUMBA v%s ATIVADO", ko = "🚀 TUMBA 메가 시스템 v%s 활성화됨", ja = "🚀 TUMBA メガシステム v%s アクティブ" },
    ["print_menu_navigate"] = { ru = "📁 Используйте вкладки для навигации", en = "📁 Use tabs to navigate", es = "📁 Usa pestañas para navegar", pt = "📁 Use abas para navegar", ko = "📁 탭으로 탐색", ja = "📁 タブでナビゲート" },
    ["print_menu_closed"] = { ru = "📱 Меню закрыто", en = "📱 Menu closed", es = "📱 Menú cerrado", pt = "📱 Menu fechado", ko = "📱 메뉴 닫힘", ja = "📱 メニュー閉じ" },

    -- Другое
    ["esp_studs"] = { ru = "%d studs", en = "%d studs", es = "%d studs", pt = "%d studs", ko = "%d 스터드", ja = "%d スタッド" },
    ["esp_hp"] = { ru = "HP: %d", en = "HP: %d", es = "HP: %d", pt = "HP: %d", ko = "HP: %d", ja = "HP: %d" }
}
